### ISSUE TITLE
Unable to start ZLS

### ISSUE THREAD

**Issue by YJ-305-A2** [redhat-developer/lsp4ij#1046]
IDE used: RustRover 2025.1.2
OS Vesion: Windows 11 24H2 26100.4061
Plugin Version: 0.13.0

The error did not occur when using the old version of the IDE, but it occurred after installing the new version of the IDE.
Even after Zig and ZLS were reinstalled, the error still existed.

Internal error prompted by IDE
```
java.util.concurrent.CompletionException: java.util.concurrent.CancellationException
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:636)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.cancel(CompletableFuture.java:2512)
	at com.redhat.devtools.lsp4ij.internal.CancellationSupport.cancel(CancellationSupport.java:263)
	at com.redhat.devtools.lsp4ij.LanguageServerWrapper.stop(LanguageServerWrapper.java:611)
	at com.redhat.devtools.lsp4ij.LanguageServerWrapper.stop(LanguageServerWrapper.java:594)
	at com.redhat.devtools.lsp4ij.LanguageServerWrapper.start(LanguageServerWrapper.java:287)
	at com.redhat.devtools.lsp4ij.LanguageServerWrapper.getInitializedServer(LanguageServerWrapper.java:1002)
	at com.redhat.devtools.lsp4ij.LanguageServiceAccessor.lambda$getLanguageServers$9(LanguageServiceAccessor.java:338)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1939)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at com.redhat.devtools.lsp4ij.LanguageServiceAccessor.lambda$getLanguageServers$11(LanguageServiceAccessor.java:355)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
Caused by: java.util.concurrent.CancellationException
	at java.base/java.util.concurrent.CompletableFuture.cancel(CompletableFuture.java:2510)
	... 24 more

```

Error message
```
Zig Language Server: Cannot start server
java.nio.file.InvalidPathException: Illegal char "> at index 0: "C:\Program Files\Zig\ZLS\zls.exe"
```

Traces Error Messages
```
com.redhat.devtools.lsp4ij.server.CannotStartProcessException: java.nio.file.InvalidPathException: Illegal char <"> at index 0: "C:\Program Files\Zig\ZLS\zls.exe"
	at com.redhat.devtools.lsp4ij.server.OSProcessStreamConnectionProvider.start(OSProcessStreamConnectionProvider.java:130)
	at com.redhat.devtools.lsp4ij.LanguageServerWrapper.lambda$start$4(LanguageServerWrapper.java:347)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
Caused by: java.nio.file.InvalidPathException: Illegal char <"> at index 0: "C:\Program Files\Zig\ZLS\zls.exe"
	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:199)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:175)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:231)
	at com.intellij.platform.core.nio.fs.DelegatingFileSystem.getPath(DelegatingFileSystem.java:94)
	at java.base/java.nio.file.Path.of(Path.java:148)
	at com.intellij.execution.configurations.GeneralCommandLine.tryGetEel(GeneralCommandLine.java:457)
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:390)
	at com.intellij.execution.process.OSProcessHandler.startProcess(OSProcessHandler.java:85)
	at com.intellij.execution.process.OSProcessHandler.<init>(OSProcessHandler.java:45)
	at com.redhat.devtools.lsp4ij.server.OSProcessStreamConnectionProvider$1.<init>(OSProcessStreamConnectionProvider.java:114)
	at com.redhat.devtools.lsp4ij.server.OSProcessStreamConnectionProvider.start(OSProcessStreamConnectionProvider.java:114)
	... 8 more
com.redhat.devtools.lsp4ij.server.CannotStartProcessException: java.nio.file.InvalidPathException: Illegal char <"> at index 0: "C:\Program Files\Zig\ZLS\zls.exe"
	at com.redhat.devtools.lsp4ij.server.OSProcessStreamConnectionProvider.start(OSProcessStreamConnectionProvider.java:130)
	at com.redhat.devtools.lsp4ij.LanguageServerWrapper.lambda$start$4(LanguageServerWrapper.java:347)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.helpAsyncBlocker(ForkJoinPool.java:1615)
	at java.base/java.util.concurrent.ForkJoinPool.helpAsyncBlocker(ForkJoinPool.java:2686)
	at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1933)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2095)
	at com.redhat.devtools.lsp4ij.internal.CompletableFutures.waitUntilDone(CompletableFutures.java:144)
	at com.redhat.devtools.lsp4ij.internal.CompletableFutures.waitUntilDone(CompletableFutures.java:111)
	at com.redhat.devtools.lsp4ij.features.semanticTokens.LSPSemanticTokensHighlightVisitor.getSemanticTokens(LSPSemanticTokensHighlightVisitor.java:120)
	at com.redhat.devtools.lsp4ij.features.semanticTokens.LSPSemanticTokensHighlightVisitor.analyze(LSPSemanticTokensHighlightVisitor.java:71)
	at com.intellij.codeInsight.daemon.impl.HighlightVisitorRunner.lambda$runVisitors$4(HighlightVisitorRunner.java:118)
	at com.intellij.concurrency.ApplierCompleter.processArrayItem(ApplierCompleter.java:121)
	at com.intellij.concurrency.ApplierCompleter.processArray(ApplierCompleter.java:205)
	at com.intellij.concurrency.ApplierCompleter.execAll(ApplierCompleter.java:171)
	at com.intellij.concurrency.JobLauncherImpl.lambda$invokeConcurrentlyUnderProgressAsync$3(JobLauncherImpl.java:109)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.tryRunReadAction$lambda$11(AnyThreadWriteThreadingSupport.kt:522)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWithTemporaryThreadLocal(AnyThreadWriteThreadingSupport.kt:204)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.tryRunReadAction(AnyThreadWriteThreadingSupport.kt:522)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1064)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$2(ApplierCompleter.java:153)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$14(CoreProgressManager.java:680)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:755)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:711)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:77)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:164)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapAndRun$1(ApplierCompleter.java:145)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:197)
	at com.intellij.concurrency.ApplierCompleter.wrapAndRun(ApplierCompleter.java:145)
	at com.intellij.concurrency.JobLauncherImpl.lambda$invokeConcurrentlyUnderProgressAsync$4(JobLauncherImpl.java:109)
	at com.intellij.concurrency.JobLauncherImpl.safeIterate(JobLauncherImpl.java:177)
	at com.intellij.concurrency.JobLauncherImpl.invokeConcurrentlyUnderProgressAsync(JobLauncherImpl.java:106)
	at com.intellij.concurrency.JobLauncherImpl.invokeConcurrentlyUnderProgress(JobLauncherImpl.java:54)
	at com.intellij.concurrency.JobLauncher.invokeConcurrentlyUnderProgress(JobLauncher.java:51)
	at com.intellij.codeInsight.daemon.impl.HighlightVisitorRunner.runVisitors(HighlightVisitorRunner.java:110)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$15(GeneralHighlightingPass.java:248)
	at com.intellij.concurrency.JobLauncherImpl.invokeConcurrentlyUnderProgressAsync(JobLauncherImpl.java:102)
	at com.intellij.concurrency.JobLauncherImpl.processConcurrentlyAsync(JobLauncherImpl.java:468)
	at com.intellij.codeInsight.daemon.impl.AnnotatorRunner.runAnnotatorsAsync(AnnotatorRunner.java:71)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:258)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectInformationWithProgress$12(GeneralHighlightingPass.java:191)
	at com.intellij.codeInsight.daemon.impl.HighlightInfoUpdaterImpl.lambda$runWithInvalidPsiRecycler$42(HighlightInfoUpdaterImpl.java:869)
	at com.intellij.codeInsight.daemon.impl.ManagedHighlighterRecycler.runWithRecycler(ManagedHighlighterRecycler.java:87)
	at com.intellij.codeInsight.daemon.impl.HighlightInfoUpdaterImpl.runWithInvalidPsiRecycler(HighlightInfoUpdaterImpl.java:850)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectInformationWithProgress$13(GeneralHighlightingPass.java:216)
	at com.intellij.codeInsight.daemon.impl.HighlightVisitorRunner.createHighlightVisitorsFor(HighlightVisitorRunner.java:82)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:113)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:88)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:435)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.use(trace.kt:28)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$3(PassExecutorService.java:431)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.tryRunReadAction$lambda$11(AnyThreadWriteThreadingSupport.kt:522)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWithTemporaryThreadLocal(AnyThreadWriteThreadingSupport.kt:204)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.tryRunReadAction(AnyThreadWriteThreadingSupport.kt:522)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1064)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$4(PassExecutorService.java:421)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$14(CoreProgressManager.java:680)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:755)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:711)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:77)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:420)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:395)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.cacheFileTypesInside(FileTypeManagerImpl.java:834)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$1(PassExecutorService.java:395)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:197)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:393)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:267)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
Caused by: java.nio.file.InvalidPathException: Illegal char <"> at index 0: "C:\Program Files\Zig\ZLS\zls.exe"
	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:199)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:175)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:231)
	at com.intellij.platform.core.nio.fs.DelegatingFileSystem.getPath(DelegatingFileSystem.java:94)
	at java.base/java.nio.file.Path.of(Path.java:148)
	at com.intellij.execution.configurations.GeneralCommandLine.tryGetEel(GeneralCommandLine.java:457)
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:390)
	at com.intellij.execution.process.OSProcessHandler.startProcess(OSProcessHandler.java:85)
	at com.intellij.execution.process.OSProcessHandler.<init>(OSProcessHandler.java:45)
	at com.redhat.devtools.lsp4ij.server.OSProcessStreamConnectionProvider$1.<init>(OSProcessStreamConnectionProvider.java:114)
	at com.redhat.devtools.lsp4ij.server.OSProcessStreamConnectionProvider.start(OSProcessStreamConnectionProvider.java:114)
	... 76 more
com.redhat.devtools.lsp4ij.server.CannotStartProcessException: java.nio.file.InvalidPathException: Illegal char <"> at index 0: "C:\Program Files\Zig\ZLS\zls.exe"
	at com.redhat.devtools.lsp4ij.server.OSProcessStreamConnectionProvider.start(OSProcessStreamConnectionProvider.java:130)
	at com.redhat.devtools.lsp4ij.LanguageServerWrapper.lambda$start$4(LanguageServerWrapper.java:347)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
Caused by: java.nio.file.InvalidPathException: Illegal char <"> at index 0: "C:\Program Files\Zig\ZLS\zls.exe"
	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:199)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:175)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:231)
	at com.intellij.platform.core.nio.fs.DelegatingFileSystem.getPath(DelegatingFileSystem.java:94)
	at java.base/java.nio.file.Path.of(Path.java:148)
	at com.intellij.execution.configurations.GeneralCommandLine.tryGetEel(GeneralCommandLine.java:457)
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:390)
	at com.intellij.execution.process.OSProcessHandler.startProcess(OSProcessHandler.java:85)
	at com.intellij.execution.process.OSProcessHandler.<init>(OSProcessHandler.java:45)
	at com.redhat.devtools.lsp4ij.server.OSProcessStreamConnectionProvider$1.<init>(OSProcessStreamConnectionProvider.java:114)
	at com.redhat.devtools.lsp4ij.server.OSProcessStreamConnectionProvider.start(OSProcessStreamConnectionProvider.java:114)
	... 8 more
com.redhat.devtools.lsp4ij.server.CannotStartProcessException: java.nio.file.InvalidPathException: Illegal char <"> at index 0: "C:\Program Files\Zig\ZLS\zls.exe"
	at com.redhat.devtools.lsp4ij.server.OSProcessStreamConnectionProvider.start(OSProcessStreamConnectionProvider.java:130)
	at com.redhat.devtools.lsp4ij.LanguageServerWrapper.lambda$start$4(LanguageServerWrapper.java:347)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
Caused by: java.nio.file.InvalidPathException: Illegal char <"> at index 0: "C:\Program Files\Zig\ZLS\zls.exe"
	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:199)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:175)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:231)
	at com.intellij.platform.core.nio.fs.DelegatingFileSystem.getPath(DelegatingFileSystem.java:94)
	at java.base/java.nio.file.Path.of(Path.java:148)
	at com.intellij.execution.configurations.GeneralCommandLine.tryGetEel(GeneralCommandLine.java:457)
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:390)
	at com.intellij.execution.process.OSProcessHandler.startProcess(OSProcessHandler.java:85)
	at com.intellij.execution.process.OSProcessHandler.<init>(OSProcessHandler.java:45)
	at com.redhat.devtools.lsp4ij.server.OSProcessStreamConnectionProvider$1.<init>(OSProcessStreamConnectionProvider.java:114)
	at com.redhat.devtools.lsp4ij.server.OSProcessStreamConnectionProvider.start(OSProcessStreamConnectionProvider.java:114)
	... 8 more
com.redhat.devtools.lsp4ij.server.CannotStartProcessException: java.nio.file.InvalidPathException: Illegal char <"> at index 0: "C:\Program Files\Zig\ZLS\zls.exe"
	at com.redhat.devtools.lsp4ij.server.OSProcessStreamConnectionProvider.start(OSProcessStreamConnectionProvider.java:130)
	at com.redhat.devtools.lsp4ij.LanguageServerWrapper.lambda$start$4(LanguageServerWrapper.java:347)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
Caused by: java.nio.file.InvalidPathException: Illegal char <"> at index 0: "C:\Program Files\Zig\ZLS\zls.exe"
	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:199)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:175)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:231)
	at com.intellij.platform.core.nio.fs.DelegatingFileSystem.getPath(DelegatingFileSystem.java:94)
	at java.base/java.nio.file.Path.of(Path.java:148)
	at com.intellij.execution.configurations.GeneralCommandLine.tryGetEel(GeneralCommandLine.java:457)
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:390)
	at com.intellij.execution.process.OSProcessHandler.startProcess(OSProcessHandler.java:85)
	at com.intellij.execution.process.OSProcessHandler.<init>(OSProcessHandler.java:45)
	at com.redhat.devtools.lsp4ij.server.OSProcessStreamConnectionProvider$1.<init>(OSProcessStreamConnectionProvider.java:114)
	at com.redhat.devtools.lsp4ij.server.OSProcessStreamConnectionProvider.start(OSProcessStreamConnectionProvider.java:114)
	... 8 more
com.redhat.devtools.lsp4ij.server.CannotStartProcessException: java.nio.file.InvalidPathException: Illegal char <"> at index 0: "C:\Program Files\Zig\ZLS\zls.exe"
	at com.redhat.devtools.lsp4ij.server.OSProcessStreamConnectionProvider.start(OSProcessStreamConnectionProvider.java:130)
	at com.redhat.devtools.lsp4ij.LanguageServerWrapper.lambda$start$4(LanguageServerWrapper.java:347)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
Caused by: java.nio.file.InvalidPathException: Illegal char <"> at index 0: "C:\Program Files\Zig\ZLS\zls.exe"
	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:199)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:175)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:231)
	at com.intellij.platform.core.nio.fs.DelegatingFileSystem.getPath(DelegatingFileSystem.java:94)
	at java.base/java.nio.file.Path.of(Path.java:148)
	at com.intellij.execution.configurations.GeneralCommandLine.tryGetEel(GeneralCommandLine.java:457)
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:390)
	at com.intellij.execution.process.OSProcessHandler.startProcess(OSProcessHandler.java:85)
	at com.intellij.execution.process.OSProcessHandler.<init>(OSProcessHandler.java:45)
	at com.redhat.devtools.lsp4ij.server.OSProcessStreamConnectionProvider$1.<init>(OSProcessStreamConnectionProvider.java:114)
	at com.redhat.devtools.lsp4ij.server.OSProcessStreamConnectionProvider.start(OSProcessStreamConnectionProvider.java:114)
	... 8 more
com.redhat.devtools.lsp4ij.server.CannotStartProcessException: java.nio.file.InvalidPathException: Illegal char <"> at index 0: "C:\Program Files\Zig\ZLS\zls.exe"
	at com.redhat.devtools.lsp4ij.server.OSProcessStreamConnectionProvider.start(OSProcessStreamConnectionProvider.java:130)
	at com.redhat.devtools.lsp4ij.LanguageServerWrapper.lambda$start$4(LanguageServerWrapper.java:347)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
Caused by: java.nio.file.InvalidPathException: Illegal char <"> at index 0: "C:\Program Files\Zig\ZLS\zls.exe"
	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:199)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:175)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:231)
	at com.intellij.platform.core.nio.fs.DelegatingFileSystem.getPath(DelegatingFileSystem.java:94)
	at java.base/java.nio.file.Path.of(Path.java:148)
	at com.intellij.execution.configurations.GeneralCommandLine.tryGetEel(GeneralCommandLine.java:457)
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:390)
	at com.intellij.execution.process.OSProcessHandler.startProcess(OSProcessHandler.java:85)
	at com.intellij.execution.process.OSProcessHandler.<init>(OSProcessHandler.java:45)
	at com.redhat.devtools.lsp4ij.server.OSProcessStreamConnectionProvider$1.<init>(OSProcessStreamConnectionProvider.java:114)
	at com.redhat.devtools.lsp4ij.server.OSProcessStreamConnectionProvider.start(OSProcessStreamConnectionProvider.java:114)
	... 8 more
com.redhat.devtools.lsp4ij.server.CannotStartProcessException: java.nio.file.InvalidPathException: Illegal char <"> at index 0: "C:\Program Files\Zig\ZLS\zls.exe"
	at com.redhat.devtools.lsp4ij.server.OSProcessStreamConnectionProvider.start(OSProcessStreamConnectionProvider.java:130)
	at com.redhat.devtools.lsp4ij.LanguageServerWrapper.lambda$start$4(LanguageServerWrapper.java:347)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
Caused by: java.nio.file.InvalidPathException: Illegal char <"> at index 0: "C:\Program Files\Zig\ZLS\zls.exe"
	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:199)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:175)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:231)
	at com.intellij.platform.core.nio.fs.DelegatingFileSystem.getPath(DelegatingFileSystem.java:94)
	at java.base/java.nio.file.Path.of(Path.java:148)
	at com.intellij.execution.configurations.GeneralCommandLine.tryGetEel(GeneralCommandLine.java:457)
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:390)
	at com.intellij.execution.process.OSProcessHandler.startProcess(OSProcessHandler.java:85)
	at com.intellij.execution.process.OSProcessHandler.<init>(OSProcessHandler.java:45)
	at com.redhat.devtools.lsp4ij.server.OSProcessStreamConnectionProvider$1.<init>(OSProcessStreamConnectionProvider.java:114)
	at com.redhat.devtools.lsp4ij.server.OSProcessStreamConnectionProvider.start(OSProcessStreamConnectionProvider.java:114)
	... 8 more
com.redhat.devtools.lsp4ij.server.CannotStartProcessException: java.nio.file.InvalidPathException: Illegal char <"> at index 0: "C:\Program Files\Zig\ZLS\zls.exe"
	at com.redhat.devtools.lsp4ij.server.OSProcessStreamConnectionProvider.start(OSProcessStreamConnectionProvider.java:130)
	at com.redhat.devtools.lsp4ij.LanguageServerWrapper.lambda$start$4(LanguageServerWrapper.java:347)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
Caused by: java.nio.file.InvalidPathException: Illegal char <"> at index 0: "C:\Program Files\Zig\ZLS\zls.exe"
	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:199)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:175)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:231)
	at com.intellij.platform.core.nio.fs.DelegatingFileSystem.getPath(DelegatingFileSystem.java:94)
	at java.base/java.nio.file.Path.of(Path.java:148)
	at com.intellij.execution.configurations.GeneralCommandLine.tryGetEel(GeneralCommandLine.java:457)
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:390)
	at com.intellij.execution.process.OSProcessHandler.startProcess(OSProcessHandler.java:85)
	at com.intellij.execution.process.OSProcessHandler.<init>(OSProcessHandler.java:45)
	at com.redhat.devtools.lsp4ij.server.OSProcessStreamConnectionProvider$1.<init>(OSProcessStreamConnectionProvider.java:114)
	at com.redhat.devtools.lsp4ij.server.OSProcessStreamConnectionProvider.start(OSProcessStreamConnectionProvider.java:114)
	... 8 more
com.redhat.devtools.lsp4ij.server.CannotStartProcessException: java.nio.file.InvalidPathException: Illegal char <"> at index 0: "C:\Program Files\Zig\ZLS\zls.exe"
	at com.redhat.devtools.lsp4ij.server.OSProcessStreamConnectionProvider.start(OSProcessStreamConnectionProvider.java:130)
	at com.redhat.devtools.lsp4ij.LanguageServerWrapper.lambda$start$4(LanguageServerWrapper.java:347)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
Caused by: java.nio.file.InvalidPathException: Illegal char <"> at index 0: "C:\Program Files\Zig\ZLS\zls.exe"
	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:199)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:175)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:231)
	at com.intellij.platform.core.nio.fs.DelegatingFileSystem.getPath(DelegatingFileSystem.java:94)
	at java.base/java.nio.file.Path.of(Path.java:148)
	at com.intellij.execution.configurations.GeneralCommandLine.tryGetEel(GeneralCommandLine.java:457)
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:390)
	at com.intellij.execution.process.OSProcessHandler.startProcess(OSProcessHandler.java:85)
	at com.intellij.execution.process.OSProcessHandler.<init>(OSProcessHandler.java:45)
	at com.redhat.devtools.lsp4ij.server.OSProcessStreamConnectionProvider$1.<init>(OSProcessStreamConnectionProvider.java:114)
	at com.redhat.devtools.lsp4ij.server.OSProcessStreamConnectionProvider.start(OSProcessStreamConnectionProvider.java:114)
	... 8 more
com.redhat.devtools.lsp4ij.server.CannotStartProcessException: java.nio.file.InvalidPathException: Illegal char <"> at index 0: "C:\Program Files\Zig\ZLS\zls.exe"
	at com.redhat.devtools.lsp4ij.server.OSProcessStreamConnectionProvider.start(OSProcessStreamConnectionProvider.java:130)
	at com.redhat.devtools.lsp4ij.LanguageServerWrapper.lambda$start$4(LanguageServerWrapper.java:347)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
Caused by: java.nio.file.InvalidPathException: Illegal char <"> at index 0: "C:\Program Files\Zig\ZLS\zls.exe"
	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:199)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:175)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:231)
	at com.intellij.platform.core.nio.fs.DelegatingFileSystem.getPath(DelegatingFileSystem.java:94)
	at java.base/java.nio.file.Path.of(Path.java:148)
	at com.intellij.execution.configurations.GeneralCommandLine.tryGetEel(GeneralCommandLine.java:457)
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:390)
	at com.intellij.execution.process.OSProcessHandler.startProcess(OSProcessHandler.java:85)
	at com.intellij.execution.process.OSProcessHandler.<init>(OSProcessHandler.java:45)
	at com.redhat.devtools.lsp4ij.server.OSProcessStreamConnectionProvider$1.<init>(OSProcessStreamConnectionProvider.java:114)
	at com.redhat.devtools.lsp4ij.server.OSProcessStreamConnectionProvider.start(OSProcessStreamConnectionProvider.java:114)
	... 8 more
com.redhat.devtools.lsp4ij.server.CannotStartProcessException: java.nio.file.InvalidPathException: Illegal char <"> at index 0: "C:\Program Files\Zig\ZLS\zls.exe"
	at com.redhat.devtools.lsp4ij.server.OSProcessStreamConnectionProvider.start(OSProcessStreamConnectionProvider.java:130)
	at com.redhat.devtools.lsp4ij.LanguageServerWrapper.lambda$start$4(LanguageServerWrapper.java:347)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
Caused by: java.nio.file.InvalidPathException: Illegal char <"> at index 0: "C:\Program Files\Zig\ZLS\zls.exe"
	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:199)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:175)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:231)
	at com.intellij.platform.core.nio.fs.DelegatingFileSystem.getPath(DelegatingFileSystem.java:94)
	at java.base/java.nio.file.Path.of(Path.java:148)
	at com.intellij.execution.configurations.GeneralCommandLine.tryGetEel(GeneralCommandLine.java:457)
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:390)
	at com.intellij.execution.process.OSProcessHandler.startProcess(OSProcessHandler.java:85)
	at com.intellij.execution.process.OSProcessHandler.<init>(OSProcessHandler.java:45)
	at com.redhat.devtools.lsp4ij.server.OSProcessStreamConnectionProvider$1.<init>(OSProcessStreamConnectionProvider.java:114)
	at com.redhat.devtools.lsp4ij.server.OSProcessStreamConnectionProvider.start(OSProcessStreamConnectionProvider.java:114)
	... 8 more
com.redhat.devtools.lsp4ij.server.CannotStartProcessException: java.nio.file.InvalidPathException: Illegal char <"> at index 0: "C:\Program Files\Zig\ZLS\zls.exe"
	at com.redhat.devtools.lsp4ij.server.OSProcessStreamConnectionProvider.start(OSProcessStreamConnectionProvider.java:130)
	at com.redhat.devtools.lsp4ij.LanguageServerWrapper.lambda$start$4(LanguageServerWrapper.java:347)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
Caused by: java.nio.file.InvalidPathException: Illegal char <"> at index 0: "C:\Program Files\Zig\ZLS\zls.exe"
	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:199)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:175)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:231)
	at com.intellij.platform.core.nio.fs.DelegatingFileSystem.getPath(DelegatingFileSystem.java:94)
	at java.base/java.nio.file.Path.of(Path.java:148)
	at com.intellij.execution.configurations.GeneralCommandLine.tryGetEel(GeneralCommandLine.java:457)
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:390)
	at com.intellij.execution.process.OSProcessHandler.startProcess(OSProcessHandler.java:85)
	at com.intellij.execution.process.OSProcessHandler.<init>(OSProcessHandler.java:45)
	at com.redhat.devtools.lsp4ij.server.OSProcessStreamConnectionProvider$1.<init>(OSProcessStreamConnectionProvider.java:114)
	at com.redhat.devtools.lsp4ij.server.OSProcessStreamConnectionProvider.start(OSProcessStreamConnectionProvider.java:114)
	... 8 more
com.redhat.devtools.lsp4ij.server.CannotStartProcessException: java.nio.file.InvalidPathException: Illegal char <"> at index 0: "C:\Program Files\Zig\ZLS\zls.exe"
	at com.redhat.devtools.lsp4ij.server.OSProcessStreamConnectionProvider.start(OSProcessStreamConnectionProvider.java:130)
	at com.redhat.devtools.lsp4ij.LanguageServerWrapper.lambda$start$4(LanguageServerWrapper.java:347)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
Caused by: java.nio.file.InvalidPathException: Illegal char <"> at index 0: "C:\Program Files\Zig\ZLS\zls.exe"
	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:199)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:175)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:231)
	at com.intellij.platform.core.nio.fs.DelegatingFileSystem.getPath(DelegatingFileSystem.java:94)
	at java.base/java.nio.file.Path.of(Path.java:148)
	at com.intellij.execution.configurations.GeneralCommandLine.tryGetEel(GeneralCommandLine.java:457)
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:390)
	at com.intellij.execution.process.OSProcessHandler.startProcess(OSProcessHandler.java:85)
	at com.intellij.execution.process.OSProcessHandler.<init>(OSProcessHandler.java:45)
	at com.redhat.devtools.lsp4ij.server.OSProcessStreamConnectionProvider$1.<init>(OSProcessStreamConnectionProvider.java:114)
	at com.redhat.devtools.lsp4ij.server.OSProcessStreamConnectionProvider.start(OSProcessStreamConnectionProvider.java:114)
	... 8 more
com.redhat.devtools.lsp4ij.server.CannotStartProcessException: java.nio.file.InvalidPathException: Illegal char <"> at index 0: "C:\Program Files\Zig\ZLS\zls.exe"
	at com.redhat.devtools.lsp4ij.server.OSProcessStreamConnectionProvider.start(OSProcessStreamConnectionProvider.java:130)
	at com.redhat.devtools.lsp4ij.LanguageServerWrapper.lambda$start$4(LanguageServerWrapper.java:347)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
Caused by: java.nio.file.InvalidPathException: Illegal char <"> at index 0: "C:\Program Files\Zig\ZLS\zls.exe"
	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:199)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:175)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:231)
	at com.intellij.platform.core.nio.fs.DelegatingFileSystem.getPath(DelegatingFileSystem.java:94)
	at java.base/java.nio.file.Path.of(Path.java:148)
	at com.intellij.execution.configurations.GeneralCommandLine.tryGetEel(GeneralCommandLine.java:457)
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:390)
	at com.intellij.execution.process.OSProcessHandler.startProcess(OSProcessHandler.java:85)
	at com.intellij.execution.process.OSProcessHandler.<init>(OSProcessHandler.java:45)
	at com.redhat.devtools.lsp4ij.server.OSProcessStreamConnectionProvider$1.<init>(OSProcessStreamConnectionProvider.java:114)
	at com.redhat.devtools.lsp4ij.server.OSProcessStreamConnectionProvider.start(OSProcessStreamConnectionProvider.java:114)
	... 8 more

```

**Comment by angelozerr** [comment]
I think the problem is because yiu have a space in your path zls exe.

Are you using a plugin which manage zls or have yiu defined this start command?

If it is a plugin I suggest that you report this issue.

If not try to emed your pat with double quote

**Comment by YJ-305-A2** [comment]
> I think the problem is because yiu have a space in your path zls exe.
> 
> Are you using a plugin which manage zls or have yiu defined this start command?
> 
> If it is a plugin I suggest that you report this issue.
> 
> If not try to emed your pat with double quote

I am also using ZigBrains plugins, is this the reason?

**Comment by angelozerr** [comment]
> > I think the problem is because yiu have a space in your path zls exe.
> > Are you using a plugin which manage zls or have yiu defined this start command?
> > If it is a plugin I suggest that you report this issue.
> > If not try to emed your pat with double quote
> 
> I am also using ZigBrains plugins, is this the reason?

Could you customize the path? If yes, try to enquote the path with double quote or choose an another path without space.

I suggest that you report the issue to the ZigBrains plugin in order to it fix the issue when it create the Process with path which have space.

**Comment by YJ-305-A2** [comment]
> > > I think the problem is because yiu have a space in your path zls exe.
> > > Are you using a plugin which manage zls or have yiu defined this start command?
> > > If it is a plugin I suggest that you report this issue.
> > > If not try to emed your pat with double quote
> > 
> > 
> > I am also using ZigBrains plugins, is this the reason?
> 
> Could you customize the path? If yes, try to enquote the path with double quote or choose an another path without space.
> 
> I suggest that you report the issue to the ZigBrains plugin in order to it fix the issue when it create the Process with path which have space.

![Image](https://github.com/user-attachments/assets/7a6e8696-84e7-4954-ad3f-0763b4b73b83)
The plugin doesn't seem to be able to customize the path. I will report this to ZigBrains later.

**Comment by angelozerr** [comment]
> The plugin doesn't seem to be able to customize the path. I will report this to ZigBrains later.

I don't understand, according your screenshot you can customize it, right?

If you move your zls.exe in a path which have not a space, is it working?

**Comment by angelozerr** [comment]
@FalsePattern please see this issue.

**Comment by FalsePattern** [comment]
Remove the double quotes around the zls executable path. I will add extra path sanitization in a hotfix to ZigBrains soon.

**Comment by FalsePattern** [comment]
Fixed in ZigBrains 25.5.1

**Comment by angelozerr** [comment]
> Fixed in ZigBrains 25.5.1


Thanks @FalsePattern !

I close the issue

**Comment by YJ-305-A2** [comment]
> Fixed in ZigBrains 25.5.1

![Image](https://github.com/user-attachments/assets/c96352df-3860-44bd-9a8a-e5cb5bef49bc)
![Image](https://github.com/user-attachments/assets/fb958d20-3645-4fd8-a63b-8f67c8d970b9)
I updated to the latest version from ZigBrains but the error persists

**Comment by YJ-305-A2** [comment]
> > The plugin doesn't seem to be able to customize the path. I will report this to ZigBrains later.
> 
> I don't understand, according your screenshot you can customize it, right?
> 
> If you move your zls.exe in a path which have not a space, is it working?

![Image](https://github.com/user-attachments/assets/0e226e06-844e-4387-88bb-2e7bea552110)
After moving to a path without spaces, LSP4IJ does not report an error and ZLS works normally.
